# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tieroptimizer.ui'
#
# Created: Tue Jun 14 23:27:47 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("TierOptimizer")
        MainWindow.setWindowTitle("Tier Optimizer")
        MainWindow.resize(595, 533)
        MainWindow.setFixedSize(595, 533)
        self.setStyleSheet("QLabel { background-color: rgba(188, 188, 188, 50); border: 1px solid rgba(188, 188, 188, 250); } QLabel[labelClass='text'] { background-color: rgba(188, 188, 188, 0); border: 1px solid rgba(188, 188, 188, 0); }")

        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.evolutionButton = QtGui.QPushButton(self.centralwidget)
        self.evolutionButton.setGeometry(QtCore.QRect(300, 460, 281, 51))
        self.evolutionButton.setObjectName("evolutionButton")
        self.initalizeButton = QtGui.QPushButton(self.centralwidget)
        self.initalizeButton.setGeometry(QtCore.QRect(10, 460, 281, 51))
        self.initalizeButton.setObjectName("initalizeButton")
        self.ranking = QtGui.QFrame(self.centralwidget)
        self.ranking.setGeometry(QtCore.QRect(10, 10, 281, 421))
        self.ranking.setFrameShape(QtGui.QFrame.StyledPanel)
        self.ranking.setFrameShadow(QtGui.QFrame.Raised)
        self.ranking.setObjectName("ranking")
        self.rank_label = QtGui.QLabel(self.ranking)
        self.rank_label.setGeometry(QtCore.QRect(10, 0, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.rank_label.setFont(font)
        self.rank_label.setProperty('labelClass', 'text')
        self.rank_label.setObjectName("rank_label")
        self.pok1 = QtGui.QLabel(self.ranking)
        self.pok1.setGeometry(QtCore.QRect(20, 30, 60, 40))
        self.pok1.setObjectName("pok1")
        self.pok2 = QtGui.QLabel(self.ranking)
        self.pok2.setGeometry(QtCore.QRect(90, 30, 60, 40))
        self.pok2.setObjectName("pok2")
        self.pok3 = QtGui.QLabel(self.ranking)
        self.pok3.setGeometry(QtCore.QRect(160, 30, 60, 40))
        self.pok3.setObjectName("pok3")
        self.pok5 = QtGui.QLabel(self.ranking)
        self.pok5.setGeometry(QtCore.QRect(120, 80, 60, 40))
        self.pok5.setObjectName("pok5")
        self.pok4 = QtGui.QLabel(self.ranking)
        self.pok4.setGeometry(QtCore.QRect(50, 80, 60, 40))
        self.pok4.setObjectName("pok4")
        self.pok6 = QtGui.QLabel(self.ranking)
        self.pok6.setGeometry(QtCore.QRect(190, 80, 60, 40))
        self.pok6.setObjectName("pok6")
        self.horizontalLayoutWidget = QtGui.QWidget(self.ranking)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 130, 272, 31))
        self.horizontalLayoutWidget.setObjectName("poketeam_0")
        self.rank2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.rank2.setContentsMargins(0, 0, 0, 0)
        self.rank2.setObjectName("rank2")
        self.rpoke1_1 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.rpoke1_1.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke1_1.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke1_1.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke1_1.setObjectName("rpoke1_1")
        self.rank2.addWidget(self.rpoke1_1)
        self.rpoke2_1 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.rpoke2_1.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke2_1.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke2_1.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke2_1.setObjectName("rpoke2_1")
        self.rank2.addWidget(self.rpoke2_1)
        self.rpoke3_1 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.rpoke3_1.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke3_1.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke3_1.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke3_1.setObjectName("rpoke3_1")
        self.rank2.addWidget(self.rpoke3_1)
        self.rpoke4_1 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.rpoke4_1.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke4_1.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke4_1.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke4_1.setObjectName("rpoke4_1")
        self.rank2.addWidget(self.rpoke4_1)
        self.rpoke5_1 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.rpoke5_1.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke5_1.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke5_1.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke5_1.setObjectName("rpoke5_1")
        self.rank2.addWidget(self.rpoke5_1)
        self.rpoke6_1 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.rpoke6_1.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke6_1.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke6_1.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke6_1.setObjectName("rpoke6_1")
        self.rank2.addWidget(self.rpoke6_1)
        self.poketeam_2 = QtGui.QWidget(self.ranking)
        self.poketeam_2.setGeometry(QtCore.QRect(0, 160, 272, 32))
        self.poketeam_2.setObjectName("poketeam_2")
        self.rank3 = QtGui.QHBoxLayout(self.poketeam_2)
        self.rank3.setContentsMargins(0, 0, 0, 0)
        self.rank3.setObjectName("rank3")
        self.rpoke1_2 = QtGui.QLabel(self.poketeam_2)
        self.rpoke1_2.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke1_2.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke1_2.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke1_2.setObjectName("rpoke1_2")
        self.rank3.addWidget(self.rpoke1_2)
        self.rpoke2_2 = QtGui.QLabel(self.poketeam_2)
        self.rpoke2_2.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke2_2.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke2_2.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke2_2.setObjectName("rpoke2_2")
        self.rank3.addWidget(self.rpoke2_2)
        self.rpoke3_2 = QtGui.QLabel(self.poketeam_2)
        self.rpoke3_2.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke3_2.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke3_2.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke3_2.setObjectName("rpoke3_2")
        self.rank3.addWidget(self.rpoke3_2)
        self.rpoke4_2 = QtGui.QLabel(self.poketeam_2)
        self.rpoke4_2.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke4_2.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke4_2.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke4_2.setObjectName("rpoke4_2")
        self.rank3.addWidget(self.rpoke4_2)
        self.rpoke5_2 = QtGui.QLabel(self.poketeam_2)
        self.rpoke5_2.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke5_2.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke5_2.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke5_2.setObjectName("rpoke5_2")
        self.rank3.addWidget(self.rpoke5_2)
        self.rpoke6_2 = QtGui.QLabel(self.poketeam_2)
        self.rpoke6_2.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke6_2.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke6_2.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke6_2.setObjectName("rpoke6_2")
        self.rank3.addWidget(self.rpoke6_2)
        self.poketeam_3 = QtGui.QWidget(self.ranking)
        self.poketeam_3.setGeometry(QtCore.QRect(0, 190, 272, 32))
        self.poketeam_3.setObjectName("poketeam_3")
        self.rank4 = QtGui.QHBoxLayout(self.poketeam_3)
        self.rank4.setContentsMargins(0, 0, 0, 0)
        self.rank4.setObjectName("rank4")
        self.rpoke1_3 = QtGui.QLabel(self.poketeam_3)
        self.rpoke1_3.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke1_3.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke1_3.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke1_3.setObjectName("rpoke1_3")
        self.rank4.addWidget(self.rpoke1_3)
        self.rpoke2_3 = QtGui.QLabel(self.poketeam_3)
        self.rpoke2_3.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke2_3.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke2_3.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke2_3.setObjectName("rpoke2_3")
        self.rank4.addWidget(self.rpoke2_3)
        self.rpoke3_3 = QtGui.QLabel(self.poketeam_3)
        self.rpoke3_3.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke3_3.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke3_3.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke3_3.setObjectName("rpoke3_3")
        self.rank4.addWidget(self.rpoke3_3)
        self.rpoke4_3 = QtGui.QLabel(self.poketeam_3)
        self.rpoke4_3.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke4_3.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke4_3.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke4_3.setObjectName("rpoke4_3")
        self.rank4.addWidget(self.rpoke4_3)
        self.rpoke5_3 = QtGui.QLabel(self.poketeam_3)
        self.rpoke5_3.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke5_3.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke5_3.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke5_3.setObjectName("rpoke5_3")
        self.rank4.addWidget(self.rpoke5_3)
        self.rpoke6_3 = QtGui.QLabel(self.poketeam_3)
        self.rpoke6_3.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke6_3.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke6_3.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke6_3.setObjectName("rpoke6_3")
        self.rank4.addWidget(self.rpoke6_3)
        self.poketeam_4 = QtGui.QWidget(self.ranking)
        self.poketeam_4.setGeometry(QtCore.QRect(0, 220, 272, 32))
        self.poketeam_4.setObjectName("poketeam_4")
        self.rank5 = QtGui.QHBoxLayout(self.poketeam_4)
        self.rank5.setContentsMargins(0, 0, 0, 0)
        self.rank5.setObjectName("rank5")
        self.rpoke1_4 = QtGui.QLabel(self.poketeam_4)
        self.rpoke1_4.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke1_4.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke1_4.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke1_4.setObjectName("rpoke1_4")
        self.rank5.addWidget(self.rpoke1_4)
        self.rpoke2_4 = QtGui.QLabel(self.poketeam_4)
        self.rpoke2_4.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke2_4.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke2_4.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke2_4.setObjectName("rpoke2_4")
        self.rank5.addWidget(self.rpoke2_4)
        self.rpoke3_4 = QtGui.QLabel(self.poketeam_4)
        self.rpoke3_4.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke3_4.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke3_4.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke3_4.setObjectName("rpoke3_4")
        self.rank5.addWidget(self.rpoke3_4)
        self.rpoke4_4 = QtGui.QLabel(self.poketeam_4)
        self.rpoke4_4.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke4_4.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke4_4.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke4_4.setObjectName("rpoke4_4")
        self.rank5.addWidget(self.rpoke4_4)
        self.rpoke5_4 = QtGui.QLabel(self.poketeam_4)
        self.rpoke5_4.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke5_4.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke5_4.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke5_4.setObjectName("rpoke5_4")
        self.rank5.addWidget(self.rpoke5_4)
        self.rpoke6_4 = QtGui.QLabel(self.poketeam_4)
        self.rpoke6_4.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke6_4.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke6_4.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke6_4.setObjectName("rpoke6_4")
        self.rank5.addWidget(self.rpoke6_4)
        self.poketeam_5 = QtGui.QWidget(self.ranking)
        self.poketeam_5.setGeometry(QtCore.QRect(0, 250, 272, 32))
        self.poketeam_5.setObjectName("poketeam_5")
        self.rank6 = QtGui.QHBoxLayout(self.poketeam_5)
        self.rank6.setContentsMargins(0, 0, 0, 0)
        self.rank6.setObjectName("rank6")
        self.rpoke1_5 = QtGui.QLabel(self.poketeam_5)
        self.rpoke1_5.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke1_5.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke1_5.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke1_5.setObjectName("rpoke1_5")
        self.rank6.addWidget(self.rpoke1_5)
        self.rpoke2_5 = QtGui.QLabel(self.poketeam_5)
        self.rpoke2_5.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke2_5.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke2_5.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke2_5.setObjectName("rpoke2_5")
        self.rank6.addWidget(self.rpoke2_5)
        self.rpoke3_5 = QtGui.QLabel(self.poketeam_5)
        self.rpoke3_5.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke3_5.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke3_5.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke3_5.setObjectName("rpoke3_5")
        self.rank6.addWidget(self.rpoke3_5)
        self.rpoke4_5 = QtGui.QLabel(self.poketeam_5)
        self.rpoke4_5.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke4_5.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke4_5.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke4_5.setObjectName("rpoke4_5")
        self.rank6.addWidget(self.rpoke4_5)
        self.rpoke5_5 = QtGui.QLabel(self.poketeam_5)
        self.rpoke5_5.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke5_5.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke5_5.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke5_5.setObjectName("rpoke5_5")
        self.rank6.addWidget(self.rpoke5_5)
        self.rpoke6_5 = QtGui.QLabel(self.poketeam_5)
        self.rpoke6_5.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke6_5.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke6_5.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke6_5.setObjectName("rpoke6_5")
        self.rank6.addWidget(self.rpoke6_5)
        self.poketeam_6 = QtGui.QWidget(self.ranking)
        self.poketeam_6.setGeometry(QtCore.QRect(0, 280, 272, 32))
        self.poketeam_6.setObjectName("poketeam_6")
        self.rank7 = QtGui.QHBoxLayout(self.poketeam_6)
        self.rank7.setContentsMargins(0, 0, 0, 0)
        self.rank7.setObjectName("rank7")
        self.rpoke1_6 = QtGui.QLabel(self.poketeam_6)
        self.rpoke1_6.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke1_6.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke1_6.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke1_6.setObjectName("rpoke1_6")
        self.rank7.addWidget(self.rpoke1_6)
        self.rpoke2_6 = QtGui.QLabel(self.poketeam_6)
        self.rpoke2_6.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke2_6.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke2_6.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke2_6.setObjectName("rpoke2_6")
        self.rank7.addWidget(self.rpoke2_6)
        self.rpoke3_6 = QtGui.QLabel(self.poketeam_6)
        self.rpoke3_6.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke3_6.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke3_6.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke3_6.setObjectName("rpoke3_6")
        self.rank7.addWidget(self.rpoke3_6)
        self.rpoke4_6 = QtGui.QLabel(self.poketeam_6)
        self.rpoke4_6.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke4_6.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke4_6.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke4_6.setObjectName("rpoke4_6")
        self.rank7.addWidget(self.rpoke4_6)
        self.rpoke5_6 = QtGui.QLabel(self.poketeam_6)
        self.rpoke5_6.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke5_6.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke5_6.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke5_6.setObjectName("rpoke5_6")
        self.rank7.addWidget(self.rpoke5_6)
        self.rpoke6_6 = QtGui.QLabel(self.poketeam_6)
        self.rpoke6_6.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke6_6.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke6_6.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke6_6.setObjectName("rpoke6_6")
        self.rank7.addWidget(self.rpoke6_6)
        self.poketeam_7 = QtGui.QWidget(self.ranking)
        self.poketeam_7.setGeometry(QtCore.QRect(0, 310, 272, 32))
        self.poketeam_7.setObjectName("poketeam_7")
        self.rank8 = QtGui.QHBoxLayout(self.poketeam_7)
        self.rank8.setContentsMargins(0, 0, 0, 0)
        self.rank8.setObjectName("rank8")
        self.rpoke1_7 = QtGui.QLabel(self.poketeam_7)
        self.rpoke1_7.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke1_7.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke1_7.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke1_7.setObjectName("rpoke1_7")
        self.rank8.addWidget(self.rpoke1_7)
        self.rpoke2_7 = QtGui.QLabel(self.poketeam_7)
        self.rpoke2_7.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke2_7.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke2_7.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke2_7.setObjectName("rpoke2_7")
        self.rank8.addWidget(self.rpoke2_7)
        self.rpoke3_7 = QtGui.QLabel(self.poketeam_7)
        self.rpoke3_7.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke3_7.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke3_7.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke3_7.setObjectName("rpoke3_7")
        self.rank8.addWidget(self.rpoke3_7)
        self.rpoke4_7 = QtGui.QLabel(self.poketeam_7)
        self.rpoke4_7.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke4_7.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke4_7.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke4_7.setObjectName("rpoke4_7")
        self.rank8.addWidget(self.rpoke4_7)
        self.rpoke5_7 = QtGui.QLabel(self.poketeam_7)
        self.rpoke5_7.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke5_7.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke5_7.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke5_7.setObjectName("rpoke5_7")
        self.rank8.addWidget(self.rpoke5_7)
        self.rpoke6_7 = QtGui.QLabel(self.poketeam_7)
        self.rpoke6_7.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke6_7.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke6_7.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke6_7.setObjectName("rpoke6_7")
        self.rank8.addWidget(self.rpoke6_7)
        self.poketeam_8 = QtGui.QWidget(self.ranking)
        self.poketeam_8.setGeometry(QtCore.QRect(0, 340, 272, 32))
        self.poketeam_8.setObjectName("poketeam_8")
        self.rank9 = QtGui.QHBoxLayout(self.poketeam_8)
        self.rank9.setContentsMargins(0, 0, 0, 0)
        self.rank9.setObjectName("rank9")
        self.rpoke1_8 = QtGui.QLabel(self.poketeam_8)
        self.rpoke1_8.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke1_8.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke1_8.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke1_8.setObjectName("rpoke1_8")
        self.rank9.addWidget(self.rpoke1_8)
        self.rpoke2_8 = QtGui.QLabel(self.poketeam_8)
        self.rpoke2_8.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke2_8.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke2_8.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke2_8.setObjectName("rpoke2_8")
        self.rank9.addWidget(self.rpoke2_8)
        self.rpoke3_8 = QtGui.QLabel(self.poketeam_8)
        self.rpoke3_8.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke3_8.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke3_8.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke3_8.setObjectName("rpoke3_8")
        self.rank9.addWidget(self.rpoke3_8)
        self.rpoke4_8 = QtGui.QLabel(self.poketeam_8)
        self.rpoke4_8.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke4_8.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke4_8.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke4_8.setObjectName("rpoke4_8")
        self.rank9.addWidget(self.rpoke4_8)
        self.rpoke5_8 = QtGui.QLabel(self.poketeam_8)
        self.rpoke5_8.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke5_8.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke5_8.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke5_8.setObjectName("rpoke5_8")
        self.rank9.addWidget(self.rpoke5_8)
        self.rpoke6_8 = QtGui.QLabel(self.poketeam_8)
        self.rpoke6_8.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke6_8.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke6_8.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke6_8.setObjectName("rpoke6_8")
        self.rank9.addWidget(self.rpoke6_8)
        self.poketeam_9 = QtGui.QWidget(self.ranking)
        self.poketeam_9.setGeometry(QtCore.QRect(0, 370, 272, 32))
        self.poketeam_9.setObjectName("poketeam_9")
        self.rank10 = QtGui.QHBoxLayout(self.poketeam_9)
        self.rank10.setContentsMargins(0, 0, 0, 0)
        self.rank10.setObjectName("rank10")
        self.rpoke1_9 = QtGui.QLabel(self.poketeam_9)
        self.rpoke1_9.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke1_9.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke1_9.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke1_9.setObjectName("rpoke1_9")
        self.rank10.addWidget(self.rpoke1_9)
        self.rpoke2_9 = QtGui.QLabel(self.poketeam_9)
        self.rpoke2_9.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke2_9.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke2_9.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke2_9.setObjectName("rpoke2_9")
        self.rank10.addWidget(self.rpoke2_9)
        self.rpoke3_9 = QtGui.QLabel(self.poketeam_9)
        self.rpoke3_9.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke3_9.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke3_9.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke3_9.setObjectName("rpoke3_9")
        self.rank10.addWidget(self.rpoke3_9)
        self.rpoke4_9 = QtGui.QLabel(self.poketeam_9)
        self.rpoke4_9.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke4_9.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke4_9.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke4_9.setObjectName("rpoke4_9")
        self.rank10.addWidget(self.rpoke4_9)
        self.rpoke5_9 = QtGui.QLabel(self.poketeam_9)
        self.rpoke5_9.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke5_9.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke5_9.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke5_9.setObjectName("rpoke5_9")
        self.rank10.addWidget(self.rpoke5_9)
        self.rpoke6_9 = QtGui.QLabel(self.poketeam_9)
        self.rpoke6_9.setMinimumSize(QtCore.QSize(40, 30))
        self.rpoke6_9.setMaximumSize(QtCore.QSize(40, 30))
        self.rpoke6_9.setBaseSize(QtCore.QSize(40, 40))
        self.rpoke6_9.setObjectName("rpoke6_9")
        self.rank10.addWidget(self.rpoke6_9)
        self.population = QtGui.QFrame(self.centralwidget)
        self.population.setGeometry(QtCore.QRect(290, 10, 291, 421))
        self.population.setFrameShape(QtGui.QFrame.StyledPanel)
        self.population.setFrameShadow(QtGui.QFrame.Raised)
        self.population.setObjectName("population")
        self.pop_label = QtGui.QLabel(self.population)
        self.pop_label.setGeometry(QtCore.QRect(10, 0, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.pop_label.setFont(font)
        self.pop_label.setObjectName("pop_label")
        self.pop_label.setProperty('labelClass', 'text')
        self.poketeam_10 = QtGui.QWidget(self.population)
        self.poketeam_10.setGeometry(QtCore.QRect(10, 20, 281, 32))
        self.poketeam_10.setObjectName("poketeam_10")
        self.pop1_1 = QtGui.QHBoxLayout(self.poketeam_10)
        self.pop1_1.setContentsMargins(0, 0, 0, 0)
        self.pop1_1.setObjectName("pop1_1")
        self.poke1_1 = QtGui.QLabel(self.poketeam_10)
        self.poke1_1.setMinimumSize(QtCore.QSize(40, 30))
        self.poke1_1.setMaximumSize(QtCore.QSize(40, 30))
        self.poke1_1.setBaseSize(QtCore.QSize(40, 40))
        self.poke1_1.setObjectName("poke1_1")
        self.pop1_1.addWidget(self.poke1_1)
        self.poke2_1 = QtGui.QLabel(self.poketeam_10)
        self.poke2_1.setMinimumSize(QtCore.QSize(40, 30))
        self.poke2_1.setMaximumSize(QtCore.QSize(40, 30))
        self.poke2_1.setBaseSize(QtCore.QSize(40, 40))
        self.poke2_1.setObjectName("poke2_1")
        self.pop1_1.addWidget(self.poke2_1)
        self.poke3_1 = QtGui.QLabel(self.poketeam_10)
        self.poke3_1.setMinimumSize(QtCore.QSize(40, 30))
        self.poke3_1.setMaximumSize(QtCore.QSize(40, 30))
        self.poke3_1.setBaseSize(QtCore.QSize(40, 40))
        self.poke3_1.setObjectName("poke3_1")
        self.pop1_1.addWidget(self.poke3_1)
        self.poke4_1 = QtGui.QLabel(self.poketeam_10)
        self.poke4_1.setMinimumSize(QtCore.QSize(40, 30))
        self.poke4_1.setMaximumSize(QtCore.QSize(40, 30))
        self.poke4_1.setBaseSize(QtCore.QSize(40, 40))
        self.poke4_1.setObjectName("poke4_1")
        self.pop1_1.addWidget(self.poke4_1)
        self.poke5_1 = QtGui.QLabel(self.poketeam_10)
        self.poke5_1.setMinimumSize(QtCore.QSize(40, 30))
        self.poke5_1.setMaximumSize(QtCore.QSize(40, 30))
        self.poke5_1.setBaseSize(QtCore.QSize(40, 40))
        self.poke5_1.setObjectName("poke5_1")
        self.pop1_1.addWidget(self.poke5_1)
        self.poke6_1 = QtGui.QLabel(self.poketeam_10)
        self.poke6_1.setMinimumSize(QtCore.QSize(40, 30))
        self.poke6_1.setMaximumSize(QtCore.QSize(40, 30))
        self.poke6_1.setBaseSize(QtCore.QSize(40, 40))
        self.poke6_1.setObjectName("poke6_1")
        self.pop1_1.addWidget(self.poke6_1)
        self.poketeam_11 = QtGui.QWidget(self.population)
        self.poketeam_11.setGeometry(QtCore.QRect(10, 50, 281, 32))
        self.poketeam_11.setObjectName("poketeam_11")
        self.pop1_2 = QtGui.QHBoxLayout(self.poketeam_11)
        self.pop1_2.setContentsMargins(0, 0, 0, 0)
        self.pop1_2.setObjectName("pop1_2")
        self.poke1_2 = QtGui.QLabel(self.poketeam_11)
        self.poke1_2.setMinimumSize(QtCore.QSize(40, 30))
        self.poke1_2.setMaximumSize(QtCore.QSize(40, 30))
        self.poke1_2.setBaseSize(QtCore.QSize(40, 40))
        self.poke1_2.setObjectName("poke1_2")
        self.pop1_2.addWidget(self.poke1_2)
        self.poke2_2 = QtGui.QLabel(self.poketeam_11)
        self.poke2_2.setMinimumSize(QtCore.QSize(40, 30))
        self.poke2_2.setMaximumSize(QtCore.QSize(40, 30))
        self.poke2_2.setBaseSize(QtCore.QSize(40, 40))
        self.poke2_2.setObjectName("poke2_2")
        self.pop1_2.addWidget(self.poke2_2)
        self.poke3_2 = QtGui.QLabel(self.poketeam_11)
        self.poke3_2.setMinimumSize(QtCore.QSize(40, 30))
        self.poke3_2.setMaximumSize(QtCore.QSize(40, 30))
        self.poke3_2.setBaseSize(QtCore.QSize(40, 40))
        self.poke3_2.setObjectName("poke3_2")
        self.pop1_2.addWidget(self.poke3_2)
        self.poke4_2 = QtGui.QLabel(self.poketeam_11)
        self.poke4_2.setMinimumSize(QtCore.QSize(40, 30))
        self.poke4_2.setMaximumSize(QtCore.QSize(40, 30))
        self.poke4_2.setBaseSize(QtCore.QSize(40, 40))
        self.poke4_2.setObjectName("poke4_2")
        self.pop1_2.addWidget(self.poke4_2)
        self.poke5_2 = QtGui.QLabel(self.poketeam_11)
        self.poke5_2.setMinimumSize(QtCore.QSize(40, 30))
        self.poke5_2.setMaximumSize(QtCore.QSize(40, 30))
        self.poke5_2.setBaseSize(QtCore.QSize(40, 40))
        self.poke5_2.setObjectName("poke5_2")
        self.pop1_2.addWidget(self.poke5_2)
        self.poke6_2 = QtGui.QLabel(self.poketeam_11)
        self.poke6_2.setMinimumSize(QtCore.QSize(40, 30))
        self.poke6_2.setMaximumSize(QtCore.QSize(40, 30))
        self.poke6_2.setBaseSize(QtCore.QSize(40, 40))
        self.poke6_2.setObjectName("poke6_2")
        self.pop1_2.addWidget(self.poke6_2)
        self.poketeam_12 = QtGui.QWidget(self.population)
        self.poketeam_12.setGeometry(QtCore.QRect(10, 80, 281, 32))
        self.poketeam_12.setObjectName("poketeam_12")
        self.pop1_3 = QtGui.QHBoxLayout(self.poketeam_12)
        self.pop1_3.setContentsMargins(0, 0, 0, 0)
        self.pop1_3.setObjectName("pop1_3")
        self.poke1_3 = QtGui.QLabel(self.poketeam_12)
        self.poke1_3.setMinimumSize(QtCore.QSize(40, 30))
        self.poke1_3.setMaximumSize(QtCore.QSize(40, 30))
        self.poke1_3.setBaseSize(QtCore.QSize(40, 40))
        self.poke1_3.setObjectName("poke1_3")
        self.pop1_3.addWidget(self.poke1_3)
        self.poke2_3 = QtGui.QLabel(self.poketeam_12)
        self.poke2_3.setMinimumSize(QtCore.QSize(40, 30))
        self.poke2_3.setMaximumSize(QtCore.QSize(40, 30))
        self.poke2_3.setBaseSize(QtCore.QSize(40, 40))
        self.poke2_3.setObjectName("poke2_3")
        self.pop1_3.addWidget(self.poke2_3)
        self.poke3_3 = QtGui.QLabel(self.poketeam_12)
        self.poke3_3.setMinimumSize(QtCore.QSize(40, 30))
        self.poke3_3.setMaximumSize(QtCore.QSize(40, 30))
        self.poke3_3.setBaseSize(QtCore.QSize(40, 40))
        self.poke3_3.setObjectName("poke3_3")
        self.pop1_3.addWidget(self.poke3_3)
        self.poke4_3 = QtGui.QLabel(self.poketeam_12)
        self.poke4_3.setMinimumSize(QtCore.QSize(40, 30))
        self.poke4_3.setMaximumSize(QtCore.QSize(40, 30))
        self.poke4_3.setBaseSize(QtCore.QSize(40, 40))
        self.poke4_3.setObjectName("poke4_3")
        self.pop1_3.addWidget(self.poke4_3)
        self.poke5_3 = QtGui.QLabel(self.poketeam_12)
        self.poke5_3.setMinimumSize(QtCore.QSize(40, 30))
        self.poke5_3.setMaximumSize(QtCore.QSize(40, 30))
        self.poke5_3.setBaseSize(QtCore.QSize(40, 40))
        self.poke5_3.setObjectName("poke5_3")
        self.pop1_3.addWidget(self.poke5_3)
        self.poke6_3 = QtGui.QLabel(self.poketeam_12)
        self.poke6_3.setMinimumSize(QtCore.QSize(40, 30))
        self.poke6_3.setMaximumSize(QtCore.QSize(40, 30))
        self.poke6_3.setBaseSize(QtCore.QSize(40, 40))
        self.poke6_3.setObjectName("poke6_3")
        self.pop1_3.addWidget(self.poke6_3)
        self.poketeam_13 = QtGui.QWidget(self.population)
        self.poketeam_13.setGeometry(QtCore.QRect(10, 110, 281, 32))
        self.poketeam_13.setObjectName("poketeam_13")
        self.pop1_4 = QtGui.QHBoxLayout(self.poketeam_13)
        self.pop1_4.setContentsMargins(0, 0, 0, 0)
        self.pop1_4.setObjectName("pop1_4")
        self.poke1_4 = QtGui.QLabel(self.poketeam_13)
        self.poke1_4.setMinimumSize(QtCore.QSize(40, 30))
        self.poke1_4.setMaximumSize(QtCore.QSize(40, 30))
        self.poke1_4.setBaseSize(QtCore.QSize(40, 40))
        self.poke1_4.setObjectName("poke1_4")
        self.pop1_4.addWidget(self.poke1_4)
        self.poke2_4 = QtGui.QLabel(self.poketeam_13)
        self.poke2_4.setMinimumSize(QtCore.QSize(40, 30))
        self.poke2_4.setMaximumSize(QtCore.QSize(40, 30))
        self.poke2_4.setBaseSize(QtCore.QSize(40, 40))
        self.poke2_4.setObjectName("poke2_4")
        self.pop1_4.addWidget(self.poke2_4)
        self.poke3_4 = QtGui.QLabel(self.poketeam_13)
        self.poke3_4.setMinimumSize(QtCore.QSize(40, 30))
        self.poke3_4.setMaximumSize(QtCore.QSize(40, 30))
        self.poke3_4.setBaseSize(QtCore.QSize(40, 40))
        self.poke3_4.setObjectName("poke3_4")
        self.pop1_4.addWidget(self.poke3_4)
        self.poke4_4 = QtGui.QLabel(self.poketeam_13)
        self.poke4_4.setMinimumSize(QtCore.QSize(40, 30))
        self.poke4_4.setMaximumSize(QtCore.QSize(40, 30))
        self.poke4_4.setBaseSize(QtCore.QSize(40, 40))
        self.poke4_4.setObjectName("poke4_4")
        self.pop1_4.addWidget(self.poke4_4)
        self.poke5_4 = QtGui.QLabel(self.poketeam_13)
        self.poke5_4.setMinimumSize(QtCore.QSize(40, 30))
        self.poke5_4.setMaximumSize(QtCore.QSize(40, 30))
        self.poke5_4.setBaseSize(QtCore.QSize(40, 40))
        self.poke5_4.setObjectName("poke5_4")
        self.pop1_4.addWidget(self.poke5_4)
        self.poke6_4 = QtGui.QLabel(self.poketeam_13)
        self.poke6_4.setMinimumSize(QtCore.QSize(40, 30))
        self.poke6_4.setMaximumSize(QtCore.QSize(40, 30))
        self.poke6_4.setBaseSize(QtCore.QSize(40, 40))
        self.poke6_4.setObjectName("poke6_4")
        self.pop1_4.addWidget(self.poke6_4)
        self.poketeam_14 = QtGui.QWidget(self.population)
        self.poketeam_14.setGeometry(QtCore.QRect(10, 140, 281, 32))
        self.poketeam_14.setObjectName("poketeam_14")
        self.pop1_5 = QtGui.QHBoxLayout(self.poketeam_14)
        self.pop1_5.setContentsMargins(0, 0, 0, 0)
        self.pop1_5.setObjectName("pop1_5")
        self.poke1_5 = QtGui.QLabel(self.poketeam_14)
        self.poke1_5.setMinimumSize(QtCore.QSize(40, 30))
        self.poke1_5.setMaximumSize(QtCore.QSize(40, 30))
        self.poke1_5.setBaseSize(QtCore.QSize(40, 40))
        self.poke1_5.setObjectName("poke1_5")
        self.pop1_5.addWidget(self.poke1_5)
        self.poke2_5 = QtGui.QLabel(self.poketeam_14)
        self.poke2_5.setMinimumSize(QtCore.QSize(40, 30))
        self.poke2_5.setMaximumSize(QtCore.QSize(40, 30))
        self.poke2_5.setBaseSize(QtCore.QSize(40, 40))
        self.poke2_5.setObjectName("poke2_5")
        self.pop1_5.addWidget(self.poke2_5)
        self.poke3_5 = QtGui.QLabel(self.poketeam_14)
        self.poke3_5.setMinimumSize(QtCore.QSize(40, 30))
        self.poke3_5.setMaximumSize(QtCore.QSize(40, 30))
        self.poke3_5.setBaseSize(QtCore.QSize(40, 40))
        self.poke3_5.setObjectName("poke3_5")
        self.pop1_5.addWidget(self.poke3_5)
        self.poke4_5 = QtGui.QLabel(self.poketeam_14)
        self.poke4_5.setMinimumSize(QtCore.QSize(40, 30))
        self.poke4_5.setMaximumSize(QtCore.QSize(40, 30))
        self.poke4_5.setBaseSize(QtCore.QSize(40, 40))
        self.poke4_5.setObjectName("poke4_5")
        self.pop1_5.addWidget(self.poke4_5)
        self.poke5_5 = QtGui.QLabel(self.poketeam_14)
        self.poke5_5.setMinimumSize(QtCore.QSize(40, 30))
        self.poke5_5.setMaximumSize(QtCore.QSize(40, 30))
        self.poke5_5.setBaseSize(QtCore.QSize(40, 40))
        self.poke5_5.setObjectName("poke5_5")
        self.pop1_5.addWidget(self.poke5_5)
        self.poke6_5 = QtGui.QLabel(self.poketeam_14)
        self.poke6_5.setMinimumSize(QtCore.QSize(40, 30))
        self.poke6_5.setMaximumSize(QtCore.QSize(40, 30))
        self.poke6_5.setBaseSize(QtCore.QSize(40, 40))
        self.poke6_5.setObjectName("poke6_5")
        self.pop1_5.addWidget(self.poke6_5)
        self.poketeam_15 = QtGui.QWidget(self.population)
        self.poketeam_15.setGeometry(QtCore.QRect(10, 170, 281, 32))
        self.poketeam_15.setObjectName("poketeam_15")
        self.pop1_6 = QtGui.QHBoxLayout(self.poketeam_15)
        self.pop1_6.setContentsMargins(0, 0, 0, 0)
        self.pop1_6.setObjectName("pop1_6")
        self.poke1_6 = QtGui.QLabel(self.poketeam_15)
        self.poke1_6.setMinimumSize(QtCore.QSize(40, 30))
        self.poke1_6.setMaximumSize(QtCore.QSize(40, 30))
        self.poke1_6.setBaseSize(QtCore.QSize(40, 40))
        self.poke1_6.setObjectName("poke1_6")
        self.pop1_6.addWidget(self.poke1_6)
        self.poke2_6 = QtGui.QLabel(self.poketeam_15)
        self.poke2_6.setMinimumSize(QtCore.QSize(40, 30))
        self.poke2_6.setMaximumSize(QtCore.QSize(40, 30))
        self.poke2_6.setBaseSize(QtCore.QSize(40, 40))
        self.poke2_6.setObjectName("poke2_6")
        self.pop1_6.addWidget(self.poke2_6)
        self.poke3_6 = QtGui.QLabel(self.poketeam_15)
        self.poke3_6.setMinimumSize(QtCore.QSize(40, 30))
        self.poke3_6.setMaximumSize(QtCore.QSize(40, 30))
        self.poke3_6.setBaseSize(QtCore.QSize(40, 40))
        self.poke3_6.setObjectName("poke3_6")
        self.pop1_6.addWidget(self.poke3_6)
        self.poke4_6 = QtGui.QLabel(self.poketeam_15)
        self.poke4_6.setMinimumSize(QtCore.QSize(40, 30))
        self.poke4_6.setMaximumSize(QtCore.QSize(40, 30))
        self.poke4_6.setBaseSize(QtCore.QSize(40, 40))
        self.poke4_6.setObjectName("poke4_6")
        self.pop1_6.addWidget(self.poke4_6)
        self.poke5_6 = QtGui.QLabel(self.poketeam_15)
        self.poke5_6.setMinimumSize(QtCore.QSize(40, 30))
        self.poke5_6.setMaximumSize(QtCore.QSize(40, 30))
        self.poke5_6.setBaseSize(QtCore.QSize(40, 40))
        self.poke5_6.setObjectName("poke5_6")
        self.pop1_6.addWidget(self.poke5_6)
        self.poke6_6 = QtGui.QLabel(self.poketeam_15)
        self.poke6_6.setMinimumSize(QtCore.QSize(40, 30))
        self.poke6_6.setMaximumSize(QtCore.QSize(40, 30))
        self.poke6_6.setBaseSize(QtCore.QSize(40, 40))
        self.poke6_6.setObjectName("poke6_6")
        self.pop1_6.addWidget(self.poke6_6)
        self.poketeam_16 = QtGui.QWidget(self.population)
        self.poketeam_16.setGeometry(QtCore.QRect(10, 200, 281, 32))
        self.poketeam_16.setObjectName("poketeam_16")
        self.pop1_7 = QtGui.QHBoxLayout(self.poketeam_16)
        self.pop1_7.setContentsMargins(0, 0, 0, 0)
        self.pop1_7.setObjectName("pop1_7")
        self.poke1_7 = QtGui.QLabel(self.poketeam_16)
        self.poke1_7.setMinimumSize(QtCore.QSize(40, 30))
        self.poke1_7.setMaximumSize(QtCore.QSize(40, 30))
        self.poke1_7.setBaseSize(QtCore.QSize(40, 40))
        self.poke1_7.setObjectName("poke1_7")
        self.pop1_7.addWidget(self.poke1_7)
        self.poke2_7 = QtGui.QLabel(self.poketeam_16)
        self.poke2_7.setMinimumSize(QtCore.QSize(40, 30))
        self.poke2_7.setMaximumSize(QtCore.QSize(40, 30))
        self.poke2_7.setBaseSize(QtCore.QSize(40, 40))
        self.poke2_7.setObjectName("poke2_7")
        self.pop1_7.addWidget(self.poke2_7)
        self.poke3_7 = QtGui.QLabel(self.poketeam_16)
        self.poke3_7.setMinimumSize(QtCore.QSize(40, 30))
        self.poke3_7.setMaximumSize(QtCore.QSize(40, 30))
        self.poke3_7.setBaseSize(QtCore.QSize(40, 40))
        self.poke3_7.setObjectName("poke3_7")
        self.pop1_7.addWidget(self.poke3_7)
        self.poke4_7 = QtGui.QLabel(self.poketeam_16)
        self.poke4_7.setMinimumSize(QtCore.QSize(40, 30))
        self.poke4_7.setMaximumSize(QtCore.QSize(40, 30))
        self.poke4_7.setBaseSize(QtCore.QSize(40, 40))
        self.poke4_7.setObjectName("poke4_7")
        self.pop1_7.addWidget(self.poke4_7)
        self.poke5_7 = QtGui.QLabel(self.poketeam_16)
        self.poke5_7.setMinimumSize(QtCore.QSize(40, 30))
        self.poke5_7.setMaximumSize(QtCore.QSize(40, 30))
        self.poke5_7.setBaseSize(QtCore.QSize(40, 40))
        self.poke5_7.setObjectName("poke5_7")
        self.pop1_7.addWidget(self.poke5_7)
        self.poke6_7 = QtGui.QLabel(self.poketeam_16)
        self.poke6_7.setMinimumSize(QtCore.QSize(40, 30))
        self.poke6_7.setMaximumSize(QtCore.QSize(40, 30))
        self.poke6_7.setBaseSize(QtCore.QSize(40, 40))
        self.poke6_7.setObjectName("poke6_7")
        self.pop1_7.addWidget(self.poke6_7)
        self.poketeam_17 = QtGui.QWidget(self.population)
        self.poketeam_17.setGeometry(QtCore.QRect(10, 230, 281, 32))
        self.poketeam_17.setObjectName("poketeam_17")
        self.pop1_8 = QtGui.QHBoxLayout(self.poketeam_17)
        self.pop1_8.setContentsMargins(0, 0, 0, 0)
        self.pop1_8.setObjectName("pop1_8")
        self.poke1_8 = QtGui.QLabel(self.poketeam_17)
        self.poke1_8.setMinimumSize(QtCore.QSize(40, 30))
        self.poke1_8.setMaximumSize(QtCore.QSize(40, 30))
        self.poke1_8.setBaseSize(QtCore.QSize(40, 40))
        self.poke1_8.setObjectName("poke1_8")
        self.pop1_8.addWidget(self.poke1_8)
        self.poke2_8 = QtGui.QLabel(self.poketeam_17)
        self.poke2_8.setMinimumSize(QtCore.QSize(40, 30))
        self.poke2_8.setMaximumSize(QtCore.QSize(40, 30))
        self.poke2_8.setBaseSize(QtCore.QSize(40, 40))
        self.poke2_8.setObjectName("poke2_8")
        self.pop1_8.addWidget(self.poke2_8)
        self.poke3_8 = QtGui.QLabel(self.poketeam_17)
        self.poke3_8.setMinimumSize(QtCore.QSize(40, 30))
        self.poke3_8.setMaximumSize(QtCore.QSize(40, 30))
        self.poke3_8.setBaseSize(QtCore.QSize(40, 40))
        self.poke3_8.setObjectName("poke3_8")
        self.pop1_8.addWidget(self.poke3_8)
        self.poke4_8 = QtGui.QLabel(self.poketeam_17)
        self.poke4_8.setMinimumSize(QtCore.QSize(40, 30))
        self.poke4_8.setMaximumSize(QtCore.QSize(40, 30))
        self.poke4_8.setBaseSize(QtCore.QSize(40, 40))
        self.poke4_8.setObjectName("poke4_8")
        self.pop1_8.addWidget(self.poke4_8)
        self.poke5_8 = QtGui.QLabel(self.poketeam_17)
        self.poke5_8.setMinimumSize(QtCore.QSize(40, 30))
        self.poke5_8.setMaximumSize(QtCore.QSize(40, 30))
        self.poke5_8.setBaseSize(QtCore.QSize(40, 40))
        self.poke5_8.setObjectName("poke5_8")
        self.pop1_8.addWidget(self.poke5_8)
        self.poke6_8 = QtGui.QLabel(self.poketeam_17)
        self.poke6_8.setMinimumSize(QtCore.QSize(40, 30))
        self.poke6_8.setMaximumSize(QtCore.QSize(40, 30))
        self.poke6_8.setBaseSize(QtCore.QSize(40, 40))
        self.poke6_8.setObjectName("poke6_8")
        self.pop1_8.addWidget(self.poke6_8)
        self.poketeam_18 = QtGui.QWidget(self.population)
        self.poketeam_18.setGeometry(QtCore.QRect(10, 260, 281, 32))
        self.poketeam_18.setObjectName("poketeam_18")
        self.pop1_9 = QtGui.QHBoxLayout(self.poketeam_18)
        self.pop1_9.setContentsMargins(0, 0, 0, 0)
        self.pop1_9.setObjectName("pop1_9")
        self.poke1_9 = QtGui.QLabel(self.poketeam_18)
        self.poke1_9.setMinimumSize(QtCore.QSize(40, 30))
        self.poke1_9.setMaximumSize(QtCore.QSize(40, 30))
        self.poke1_9.setBaseSize(QtCore.QSize(40, 40))
        self.poke1_9.setObjectName("poke1_9")
        self.pop1_9.addWidget(self.poke1_9)
        self.poke2_9 = QtGui.QLabel(self.poketeam_18)
        self.poke2_9.setMinimumSize(QtCore.QSize(40, 30))
        self.poke2_9.setMaximumSize(QtCore.QSize(40, 30))
        self.poke2_9.setBaseSize(QtCore.QSize(40, 40))
        self.poke2_9.setObjectName("poke2_9")
        self.pop1_9.addWidget(self.poke2_9)
        self.poke3_9 = QtGui.QLabel(self.poketeam_18)
        self.poke3_9.setMinimumSize(QtCore.QSize(40, 30))
        self.poke3_9.setMaximumSize(QtCore.QSize(40, 30))
        self.poke3_9.setBaseSize(QtCore.QSize(40, 40))
        self.poke3_9.setObjectName("poke3_9")
        self.pop1_9.addWidget(self.poke3_9)
        self.poke4_9 = QtGui.QLabel(self.poketeam_18)
        self.poke4_9.setMinimumSize(QtCore.QSize(40, 30))
        self.poke4_9.setMaximumSize(QtCore.QSize(40, 30))
        self.poke4_9.setBaseSize(QtCore.QSize(40, 40))
        self.poke4_9.setObjectName("poke4_9")
        self.pop1_9.addWidget(self.poke4_9)
        self.poke5_9 = QtGui.QLabel(self.poketeam_18)
        self.poke5_9.setMinimumSize(QtCore.QSize(40, 30))
        self.poke5_9.setMaximumSize(QtCore.QSize(40, 30))
        self.poke5_9.setBaseSize(QtCore.QSize(40, 40))
        self.poke5_9.setObjectName("poke5_9")
        self.pop1_9.addWidget(self.poke5_9)
        self.poke6_9 = QtGui.QLabel(self.poketeam_18)
        self.poke6_9.setMinimumSize(QtCore.QSize(40, 30))
        self.poke6_9.setMaximumSize(QtCore.QSize(40, 30))
        self.poke6_9.setBaseSize(QtCore.QSize(40, 40))
        self.poke6_9.setObjectName("poke6_9")
        self.pop1_9.addWidget(self.poke6_9)
        self.poketeam_19 = QtGui.QWidget(self.population)
        self.poketeam_19.setGeometry(QtCore.QRect(10, 290, 281, 32))
        self.poketeam_19.setObjectName("poketeam_19")
        self.pop1_10 = QtGui.QHBoxLayout(self.poketeam_19)
        self.pop1_10.setContentsMargins(0, 0, 0, 0)
        self.pop1_10.setObjectName("pop1_10")
        self.poke1_10 = QtGui.QLabel(self.poketeam_19)
        self.poke1_10.setMinimumSize(QtCore.QSize(40, 30))
        self.poke1_10.setMaximumSize(QtCore.QSize(40, 30))
        self.poke1_10.setBaseSize(QtCore.QSize(40, 40))
        self.poke1_10.setObjectName("poke1_10")
        self.pop1_10.addWidget(self.poke1_10)
        self.poke2_10 = QtGui.QLabel(self.poketeam_19)
        self.poke2_10.setMinimumSize(QtCore.QSize(40, 30))
        self.poke2_10.setMaximumSize(QtCore.QSize(40, 30))
        self.poke2_10.setBaseSize(QtCore.QSize(40, 40))
        self.poke2_10.setObjectName("poke2_10")
        self.pop1_10.addWidget(self.poke2_10)
        self.poke3_10 = QtGui.QLabel(self.poketeam_19)
        self.poke3_10.setMinimumSize(QtCore.QSize(40, 30))
        self.poke3_10.setMaximumSize(QtCore.QSize(40, 30))
        self.poke3_10.setBaseSize(QtCore.QSize(40, 40))
        self.poke3_10.setObjectName("poke3_10")
        self.pop1_10.addWidget(self.poke3_10)
        self.poke4_10 = QtGui.QLabel(self.poketeam_19)
        self.poke4_10.setMinimumSize(QtCore.QSize(40, 30))
        self.poke4_10.setMaximumSize(QtCore.QSize(40, 30))
        self.poke4_10.setBaseSize(QtCore.QSize(40, 40))
        self.poke4_10.setObjectName("poke4_10")
        self.pop1_10.addWidget(self.poke4_10)
        self.poke5_10 = QtGui.QLabel(self.poketeam_19)
        self.poke5_10.setMinimumSize(QtCore.QSize(40, 30))
        self.poke5_10.setMaximumSize(QtCore.QSize(40, 30))
        self.poke5_10.setBaseSize(QtCore.QSize(40, 40))
        self.poke5_10.setObjectName("poke5_10")
        self.pop1_10.addWidget(self.poke5_10)
        self.poke6_10 = QtGui.QLabel(self.poketeam_19)
        self.poke6_10.setMinimumSize(QtCore.QSize(40, 30))
        self.poke6_10.setMaximumSize(QtCore.QSize(40, 30))
        self.poke6_10.setBaseSize(QtCore.QSize(40, 40))
        self.poke6_10.setObjectName("poke6_10")
        self.pop1_10.addWidget(self.poke6_10)
        self.poketeam_20 = QtGui.QWidget(self.population)
        self.poketeam_20.setGeometry(QtCore.QRect(10, 320, 281, 32))
        self.poketeam_20.setObjectName("poketeam_20")
        self.pop1_11 = QtGui.QHBoxLayout(self.poketeam_20)
        self.pop1_11.setContentsMargins(0, 0, 0, 0)
        self.pop1_11.setObjectName("pop1_11")
        self.poke1_11 = QtGui.QLabel(self.poketeam_20)
        self.poke1_11.setMinimumSize(QtCore.QSize(40, 30))
        self.poke1_11.setMaximumSize(QtCore.QSize(40, 30))
        self.poke1_11.setBaseSize(QtCore.QSize(40, 40))
        self.poke1_11.setObjectName("poke1_11")
        self.pop1_11.addWidget(self.poke1_11)
        self.poke2_11 = QtGui.QLabel(self.poketeam_20)
        self.poke2_11.setMinimumSize(QtCore.QSize(40, 30))
        self.poke2_11.setMaximumSize(QtCore.QSize(40, 30))
        self.poke2_11.setBaseSize(QtCore.QSize(40, 40))
        self.poke2_11.setObjectName("poke2_11")
        self.pop1_11.addWidget(self.poke2_11)
        self.poke3_11 = QtGui.QLabel(self.poketeam_20)
        self.poke3_11.setMinimumSize(QtCore.QSize(40, 30))
        self.poke3_11.setMaximumSize(QtCore.QSize(40, 30))
        self.poke3_11.setBaseSize(QtCore.QSize(40, 40))
        self.poke3_11.setObjectName("poke3_11")
        self.pop1_11.addWidget(self.poke3_11)
        self.poke4_11 = QtGui.QLabel(self.poketeam_20)
        self.poke4_11.setMinimumSize(QtCore.QSize(40, 30))
        self.poke4_11.setMaximumSize(QtCore.QSize(40, 30))
        self.poke4_11.setBaseSize(QtCore.QSize(40, 40))
        self.poke4_11.setObjectName("poke4_11")
        self.pop1_11.addWidget(self.poke4_11)
        self.poke5_11 = QtGui.QLabel(self.poketeam_20)
        self.poke5_11.setMinimumSize(QtCore.QSize(40, 30))
        self.poke5_11.setMaximumSize(QtCore.QSize(40, 30))
        self.poke5_11.setBaseSize(QtCore.QSize(40, 40))
        self.poke5_11.setObjectName("poke5_11")
        self.pop1_11.addWidget(self.poke5_11)
        self.poke6_11 = QtGui.QLabel(self.poketeam_20)
        self.poke6_11.setMinimumSize(QtCore.QSize(40, 30))
        self.poke6_11.setMaximumSize(QtCore.QSize(40, 30))
        self.poke6_11.setBaseSize(QtCore.QSize(40, 40))
        self.poke6_11.setObjectName("poke6_11")
        self.pop1_11.addWidget(self.poke6_11)
        self.poketeam_21 = QtGui.QWidget(self.population)
        self.poketeam_21.setGeometry(QtCore.QRect(10, 350, 281, 32))
        self.poketeam_21.setObjectName("poketeam_21")
        self.pop1_12 = QtGui.QHBoxLayout(self.poketeam_21)
        self.pop1_12.setContentsMargins(0, 0, 0, 0)
        self.pop1_12.setObjectName("pop1_12")
        self.poke1_12 = QtGui.QLabel(self.poketeam_21)
        self.poke1_12.setMinimumSize(QtCore.QSize(40, 30))
        self.poke1_12.setMaximumSize(QtCore.QSize(40, 30))
        self.poke1_12.setBaseSize(QtCore.QSize(40, 40))
        self.poke1_12.setObjectName("poke1_12")
        self.pop1_12.addWidget(self.poke1_12)
        self.poke2_12 = QtGui.QLabel(self.poketeam_21)
        self.poke2_12.setMinimumSize(QtCore.QSize(40, 30))
        self.poke2_12.setMaximumSize(QtCore.QSize(40, 30))
        self.poke2_12.setBaseSize(QtCore.QSize(40, 40))
        self.poke2_12.setObjectName("poke2_12")
        self.pop1_12.addWidget(self.poke2_12)
        self.poke3_12 = QtGui.QLabel(self.poketeam_21)
        self.poke3_12.setMinimumSize(QtCore.QSize(40, 30))
        self.poke3_12.setMaximumSize(QtCore.QSize(40, 30))
        self.poke3_12.setBaseSize(QtCore.QSize(40, 40))
        self.poke3_12.setObjectName("poke3_12")
        self.pop1_12.addWidget(self.poke3_12)
        self.poke4_12 = QtGui.QLabel(self.poketeam_21)
        self.poke4_12.setMinimumSize(QtCore.QSize(40, 30))
        self.poke4_12.setMaximumSize(QtCore.QSize(40, 30))
        self.poke4_12.setBaseSize(QtCore.QSize(40, 40))
        self.poke4_12.setObjectName("poke4_12")
        self.pop1_12.addWidget(self.poke4_12)
        self.poke5_12 = QtGui.QLabel(self.poketeam_21)
        self.poke5_12.setMinimumSize(QtCore.QSize(40, 30))
        self.poke5_12.setMaximumSize(QtCore.QSize(40, 30))
        self.poke5_12.setBaseSize(QtCore.QSize(40, 40))
        self.poke5_12.setObjectName("poke5_12")
        self.pop1_12.addWidget(self.poke5_12)
        self.poke6_12 = QtGui.QLabel(self.poketeam_21)
        self.poke6_12.setMinimumSize(QtCore.QSize(40, 30))
        self.poke6_12.setMaximumSize(QtCore.QSize(40, 30))
        self.poke6_12.setBaseSize(QtCore.QSize(40, 40))
        self.poke6_12.setObjectName("poke6_12")
        self.pop1_12.addWidget(self.poke6_12)
        self.poketeam_22 = QtGui.QWidget(self.population)
        self.poketeam_22.setGeometry(QtCore.QRect(10, 380, 281, 32))
        self.poketeam_22.setObjectName("poketeam_22")
        self.pop1_13 = QtGui.QHBoxLayout(self.poketeam_22)
        self.pop1_13.setContentsMargins(0, 0, 0, 0)
        self.pop1_13.setObjectName("pop1_13")
        self.poke1_13 = QtGui.QLabel(self.poketeam_22)
        self.poke1_13.setMinimumSize(QtCore.QSize(40, 30))
        self.poke1_13.setMaximumSize(QtCore.QSize(40, 30))
        self.poke1_13.setBaseSize(QtCore.QSize(40, 40))
        self.poke1_13.setObjectName("poke1_13")
        self.pop1_13.addWidget(self.poke1_13)
        self.poke2_13 = QtGui.QLabel(self.poketeam_22)
        self.poke2_13.setMinimumSize(QtCore.QSize(40, 30))
        self.poke2_13.setMaximumSize(QtCore.QSize(40, 30))
        self.poke2_13.setBaseSize(QtCore.QSize(40, 40))
        self.poke2_13.setObjectName("poke2_13")
        self.pop1_13.addWidget(self.poke2_13)
        self.poke3_13 = QtGui.QLabel(self.poketeam_22)
        self.poke3_13.setMinimumSize(QtCore.QSize(40, 30))
        self.poke3_13.setMaximumSize(QtCore.QSize(40, 30))
        self.poke3_13.setBaseSize(QtCore.QSize(40, 40))
        self.poke3_13.setObjectName("poke3_13")
        self.pop1_13.addWidget(self.poke3_13)
        self.poke4_13 = QtGui.QLabel(self.poketeam_22)
        self.poke4_13.setMinimumSize(QtCore.QSize(40, 30))
        self.poke4_13.setMaximumSize(QtCore.QSize(40, 30))
        self.poke4_13.setBaseSize(QtCore.QSize(40, 40))
        self.poke4_13.setObjectName("poke4_13")
        self.pop1_13.addWidget(self.poke4_13)
        self.poke5_13 = QtGui.QLabel(self.poketeam_22)
        self.poke5_13.setMinimumSize(QtCore.QSize(40, 30))
        self.poke5_13.setMaximumSize(QtCore.QSize(40, 30))
        self.poke5_13.setBaseSize(QtCore.QSize(40, 40))
        self.poke5_13.setObjectName("poke5_13")
        self.pop1_13.addWidget(self.poke5_13)
        self.poke6_13 = QtGui.QLabel(self.poketeam_22)
        self.poke6_13.setMinimumSize(QtCore.QSize(40, 30))
        self.poke6_13.setMaximumSize(QtCore.QSize(40, 30))
        self.poke6_13.setBaseSize(QtCore.QSize(40, 40))
        self.poke6_13.setObjectName("poke6_13")
        self.pop1_13.addWidget(self.poke6_13)
        self.progress = QtGui.QProgressBar(self.centralwidget)
        self.progress.setGeometry(QtCore.QRect(10, 430, 571, 23))
        self.progress.setMaximum(160)
        self.progress.setProperty("value", 0)
        self.progress.setTextVisible(False)
        self.progress.setFormat("")
        self.progress.setObjectName("progress")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Tier Optimizer", None, QtGui.QApplication.UnicodeUTF8))
        self.evolutionButton.setText(QtGui.QApplication.translate("MainWindow", "Calculate Generations", None, QtGui.QApplication.UnicodeUTF8))
        self.initalizeButton.setText(QtGui.QApplication.translate("MainWindow", "Initialize Generation", None, QtGui.QApplication.UnicodeUTF8))
        self.rank_label.setText(QtGui.QApplication.translate("MainWindow", "Ranking", None, QtGui.QApplication.UnicodeUTF8))
        self.pop_label.setText(QtGui.QApplication.translate("MainWindow", "Population", None, QtGui.QApplication.UnicodeUTF8))

